export const DOCUMENT_TYPES = ['KTP','NPWP','BANK_STATEMENT','SALARY_SLIP','LOAN_APPLICATION','INVOICE','UNKNOWN'];

export function normalizeName(v=''){return String(v).normalize('NFKD').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim().toUpperCase()}
export function normalizeCurrency(v=''){return String(v).replace(/[^0-9]/g,'')}
export function normalizeIdentifier(v=''){return String(v).replace(/[^A-Za-z0-9]/g,'').toUpperCase()}
export function normalizeDate(v=''){const s=String(v).trim();const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:s.toUpperCase()}
export function normalizeField(name,value){const n=String(name).toLowerCase();if(n.includes('name')||n.includes('holder'))return normalizeName(value);if(n.includes('salary')||n.includes('balance')||n.includes('amount')||n.includes('allowance')||n.includes('deduction'))return normalizeCurrency(value);if(n.includes('date')||n.includes('period'))return normalizeDate(value);if(n.includes('nik')||n.includes('npwp')||n.includes('number')||n.includes('account'))return normalizeIdentifier(value);return String(value??'').trim().replace(/\s+/g,' ').toUpperCase()}

const schema=(id,label,fields)=>({id,label,enabled:true,fields:fields.map(([name,label,type='string',required=false])=>({id:`sf_${id}_${name}`,name,label,type,required}))});
export function defaultSchemas(){return [
 schema('KTP','KTP / Identity Card',[['nik','NIK','identifier',true],['name','Full Name','name',true],['birth_place','Birth Place'],['birth_date','Birth Date','date'],['gender','Gender'],['address','Address']]),
 schema('NPWP','NPWP / Tax ID',[['npwp','NPWP Number','identifier',true],['name','Taxpayer Name','name',true],['address','Address']]),
 schema('SALARY_SLIP','Salary Slip',[['employee_name','Employee Name','name',true],['company_name','Company Name'],['period','Period','date'],['basic_salary','Basic Salary','currency'],['allowances','Allowances','currency'],['deductions','Deductions','currency'],['net_salary','Net Salary','currency',true]]),
 schema('BANK_STATEMENT','Bank Statement',[['account_holder','Account Holder','name',true],['account_number','Account Number','identifier'],['period','Period','date'],['opening_balance','Opening Balance','currency'],['closing_balance','Closing Balance','currency']]),
 schema('LOAN_APPLICATION','Loan Application',[['applicant_name','Applicant Name','name',true],['nik','NIK','identifier',true],['npwp','NPWP','identifier'],['requested_amount','Requested Amount','currency'],['application_date','Application Date','date']]),
 schema('INVOICE','Invoice',[['invoice_number','Invoice Number','identifier',true],['invoice_date','Invoice Date','date'],['vendor_name','Vendor Name','name'],['customer_name','Customer Name','name'],['amount','Amount','currency',true]])
]}
export function defaultRules(){return [
 {id:'RULE-001',name:'KTP name vs NPWP name',type:'compare',sourceDoc:'KTP',sourceFields:['name'],targetDoc:'NPWP',targetFields:['name'],label:'Customer Name',severity:'HIGH',enabled:true},
 {id:'RULE-002',name:'KTP name vs Loan Application',type:'compare',sourceDoc:'KTP',sourceFields:['name'],targetDoc:'LOAN_APPLICATION',targetFields:['applicant_name'],label:'Customer Name',severity:'HIGH',enabled:true},
 {id:'RULE-003',name:'KTP NIK vs Loan Application',type:'compare',sourceDoc:'KTP',sourceFields:['nik'],targetDoc:'LOAN_APPLICATION',targetFields:['nik'],label:'NIK',severity:'CRITICAL',enabled:true},
 {id:'RULE-004',name:'Salary employee vs KTP',type:'compare',sourceDoc:'SALARY_SLIP',sourceFields:['employee_name'],targetDoc:'KTP',targetFields:['name'],label:'Employee Name',severity:'HIGH',enabled:true},
 {id:'RULE-005',name:'Bank holder vs KTP',type:'compare',sourceDoc:'BANK_STATEMENT',sourceFields:['account_holder'],targetDoc:'KTP',targetFields:['name'],label:'Account Holder',severity:'HIGH',enabled:true},
 {id:'RULE-006',name:'KTP NIK required',type:'required',sourceDoc:'KTP',sourceFields:['nik'],label:'KTP NIK',severity:'CRITICAL',enabled:true},
 {id:'RULE-007',name:'NPWP number required',type:'required',sourceDoc:'NPWP',sourceFields:['npwp'],label:'NPWP Number',severity:'HIGH',enabled:true}
]}
export function defaultSettings(){const routing={};for(const t of DOCUMENT_TYPES)routing[t]={provider:'openai',model:'gpt-6-luna'};return {providers:{
 openai:{id:'openai',name:'OpenAI',kind:'openai_responses',enabled:true,baseUrl:'https://api.openai.com/v1',model:'gpt-6-luna',models:['gpt-6-luna']},
 gemini:{id:'gemini',name:'Google Gemini',kind:'openai_compatible',enabled:true,baseUrl:'https://generativelanguage.googleapis.com/v1beta/openai',model:'gemini-3-flash-preview',models:['gemini-3-flash-preview']},
 qwen:{id:'qwen',name:'Alibaba Qwen',kind:'openai_compatible',enabled:true,baseUrl:'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',model:'qwen-vl-max',models:['qwen-vl-max','qwen-plus']},
 kimi:{id:'kimi',name:'Kimi / Moonshot',kind:'openai_compatible',enabled:true,baseUrl:'https://api.moonshot.ai/v1',model:'kimi-k2.5',models:['kimi-k2.5']},
 deepseek:{id:'deepseek',name:'DeepSeek',kind:'openai_compatible',enabled:true,baseUrl:'https://api.deepseek.com',model:'deepseek-chat',models:['deepseek-chat']},
 ollama:{id:'ollama',name:'Ollama Local',kind:'ollama',enabled:true,baseUrl:'http://localhost:11434',model:'',models:[]},
 custom:{id:'custom',name:'Custom OpenAI-compatible',kind:'openai_compatible',enabled:false,baseUrl:'',model:'',models:[]}},routing,fallback:{enabled:false,provider:'openai',model:'gpt-6-luna'},thresholds:{needsReview:.75,highConfidence:.9}}}

function field(doc,names){return doc?.fields?.find(f=>names.includes(f.fieldName))}
function value(f){return f?(f.verifiedValue||f.normalizedValue||''):''}
export function validateCase(c,idFn=()=>crypto.randomUUID(),rules=defaultRules()){
 const docs={};for(const d of c.documents||[])if(!docs[d.documentType])docs[d.documentType]=d;const out=[];
 for(const r of rules.filter(x=>x.enabled!==false)){
  if(r.type==='compare'){const a=docs[r.sourceDoc],b=docs[r.targetDoc];if(!a&&!b)continue;const fa=field(a,r.sourceFields||[]),fb=field(b,r.targetFields||[]);let status='MATCH',message='Values match';if(!a||!b||!fa||!fb||!value(fa)||!value(fb)){status='MISSING';message='Required comparison value or document is missing'}else if(fa.confidence<.75||fb.confidence<.75||fa.needsReview||fb.needsReview){status='LOW_CONFIDENCE';message='One or more values need human review'}else if(value(fa)!==value(fb)){status='MISMATCH';message='Values differ across documents'}out.push({id:idFn('val'),caseId:c.id,ruleId:r.id,ruleName:r.name,severity:r.severity||'MEDIUM',fieldName:r.label||r.name,sourceDocument:a?.documentType||'MISSING',targetDocument:b?.documentType||'MISSING',sourceValue:fa?.rawValue||'—',targetValue:fb?.rawValue||'—',sourceFieldId:fa?.id||null,targetFieldId:fb?.id||null,status,message});
  } else if(r.type==='required'){const a=docs[r.sourceDoc],fa=field(a,r.sourceFields||[]);let status='MATCH',message='Required value is present';if(!a||!fa||!value(fa)){status='MISSING';message='Required field is missing'}else if(fa.confidence<.75||fa.needsReview){status='LOW_CONFIDENCE';message='Required field has low confidence'}out.push({id:idFn('val'),caseId:c.id,ruleId:r.id,ruleName:r.name,severity:r.severity||'MEDIUM',fieldName:r.label||r.name,sourceDocument:a?.documentType||'MISSING',targetDocument:'Required Field',sourceValue:fa?.rawValue||'—',targetValue:'Required',sourceFieldId:fa?.id||null,targetFieldId:null,status,message});}
 }
 return out;
}
export function deriveStatus(c){if(['APPROVED','REJECTED'].includes(c.status))return c.status;if((c.documents||[]).some(d=>d.processingStatus==='PROCESSING'))return 'PROCESSING';if((c.validations||[]).some(v=>v.status!=='MATCH')||(c.documents||[]).some(d=>(d.fields||[]).some(f=>f.needsReview&&!['VERIFIED','CORRECTED'].includes(f.verificationStatus))))return 'NEEDS_REVIEW';return (c.documents||[]).length?'READY_FOR_REVIEW':'NEW'}
export function buildReviewQueue(cases=[]){const rank={HIGH:3,MEDIUM:2,LOW:1};return cases.filter(c=>c.status==='NEEDS_REVIEW').map(c=>{const v=c.validations||[],m=v.filter(x=>x.status==='MISMATCH').length,missing=v.filter(x=>x.status==='MISSING').length,low=v.filter(x=>x.status==='LOW_CONFIDENCE').length,lowFields=(c.documents||[]).flatMap(d=>(d.fields||[]).filter(f=>f.needsReview).map(f=>({documentId:d.id,documentType:d.documentType,fieldId:f.id,fieldName:f.fieldName,value:f.rawValue,confidence:f.confidence})));const priority=(v.some(x=>x.severity==='CRITICAL'&&x.status!=='MATCH')||m)?'HIGH':missing?'MEDIUM':'LOW';return {caseId:c.id,caseNumber:c.caseNumber,customerName:c.customerName,caseType:c.caseType,status:c.status,priority,mismatch:m,missing,lowConfidence:low+lowFields.length,issues:m+missing+low+lowFields.length,updatedAt:c.updatedAt,lowFields}}).sort((a,b)=>rank[b.priority]-rank[a.priority]||new Date(b.updatedAt)-new Date(a.updatedAt))}
export function ensureDefaults(db){db.settings={...defaultSettings(),...(db.settings||{}),providers:{...defaultSettings().providers,...(db.settings?.providers||{})},routing:{...defaultSettings().routing,...(db.settings?.routing||{})}};db.schemas=Array.isArray(db.schemas)&&db.schemas.length?db.schemas:defaultSchemas();db.rules=Array.isArray(db.rules)&&db.rules.length?db.rules:defaultRules();db.cases=Array.isArray(db.cases)?db.cases:[];db.referenceFields=Array.isArray(db.referenceFields)?db.referenceFields:[];db.comparisonHistory=Array.isArray(db.comparisonHistory)?db.comparisonHistory:[];return db}

export function levenshtein(a='',b=''){a=String(a);b=String(b);if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[b.length]}
export function textSimilarity(a='',b=''){const aa=normalizeName(a),bb=normalizeName(b);if(!aa&&!bb)return 100;if(!aa||!bb)return 0;if(aa===bb)return 100;const lev=1-levenshtein(aa,bb)/Math.max(aa.length,bb.length);const ta=new Set(aa.split(/\s+/).filter(Boolean)),tb=new Set(bb.split(/\s+/).filter(Boolean)),inter=[...ta].filter(x=>tb.has(x)).length,union=new Set([...ta,...tb]).size||1,jacc=inter/union;return Math.max(0,Math.min(100,(lev*.7+jacc*.3)*100))}
export function fieldNameSimilarity(a='',b=''){return textSimilarity(String(a).replaceAll('_',' '),String(b).replaceAll('_',' '))}
export function compareValue(type='string',a='',b=''){const t=String(type||'string').toLowerCase();if(a===undefined||a===null||b===undefined||b===null||String(a).trim()===''||String(b).trim()==='')return 0;const na=normalizeField(t==='name'?'name':t==='currency'?'amount':t==='identifier'?'number':t==='date'?'date':'text',a),nb=normalizeField(t==='name'?'name':t==='currency'?'amount':t==='identifier'?'number':t==='date'?'date':'text',b);if(na===nb)return 100;if(t==='currency'||t==='number'||t==='numeric'){const x=Number(na),y=Number(nb);if(Number.isFinite(x)&&Number.isFinite(y)){const base=Math.max(Math.abs(x),Math.abs(y),1);return Math.max(0,Math.min(100,(1-Math.abs(x-y)/base)*100))}}if(t==='identifier'||t==='date')return Math.max(0,Math.min(100,(1-levenshtein(na,nb)/Math.max(na.length,nb.length,1))*100));return textSimilarity(na,nb)}
export function matchExtractedField(fields=[],targetName='',used=new Set()){let best=null,bestScore=-1;for(const f of fields){if(used.has(f))continue;const s=fieldNameSimilarity(targetName,f.fieldName||f.field_name||'');if(s>bestScore){bestScore=s;best=f}}return bestScore>=45?{field:best,score:bestScore}:{field:null,score:bestScore}}
export function compareReferenceToFields(referenceFields=[],fields=[]){const used=new Set();return referenceFields.map(r=>{const m=matchExtractedField(fields,r.name,used);if(m.field)used.add(m.field);const actual=m.field?.rawValue??m.field?.value??'';const similarity=compareValue(r.type||'string',r.value,actual);return {field:r.name,label:r.label||r.name,type:r.type||'string',leftValue:r.value,rightValue:actual,leftSource:'Reference Table',rightSource:'Uploaded Document',fieldMatch:Math.round(Math.max(0,m.score)),similarity:Math.round(similarity*100)/100,status:similarity>=95?'MATCH':similarity>=75?'REVIEW':'MISMATCH'}})}
export function inferComparisonType(name=''){const n=String(name).toLowerCase();if(n.includes('name')||n.includes('holder')||n.includes('applicant')||n.includes('employee')||n.includes('vendor')||n.includes('customer'))return 'name';if(n.includes('amount')||n.includes('salary')||n.includes('balance')||n.includes('total')||n.includes('price'))return 'currency';if(n.includes('date')||n.includes('period'))return 'date';if(n.includes('nik')||n.includes('npwp')||n.includes('number')||n.includes('account')||n.endsWith('_id'))return 'identifier';return 'string'}
export function compareFieldSets(aFields=[],bFields=[]){const used=new Set(),rows=[];for(const a of aFields){const m=matchExtractedField(bFields,a.fieldName||a.field_name||'',used);if(m.field)used.add(m.field);const b=m.field,type=inferComparisonType(a.fieldName||a.field_name||''),av=a.rawValue??a.value??'',bv=b?.rawValue??b?.value??'';const similarity=compareValue(type,av,bv);rows.push({field:a.fieldName||a.field_name,label:(a.fieldName||a.field_name||'').replaceAll('_',' '),type,leftValue:av,rightValue:bv,leftSource:'File A',rightSource:'File B',fieldMatch:Math.round(Math.max(0,m.score)),similarity:Math.round(similarity*100)/100,status:similarity>=95?'MATCH':similarity>=75?'REVIEW':'MISMATCH'})}for(const b of bFields){if(used.has(b))continue;rows.push({field:b.fieldName||b.field_name,label:(b.fieldName||b.field_name||'').replaceAll('_',' '),type:inferComparisonType(b.fieldName||b.field_name||''),leftValue:'',rightValue:b.rawValue??b.value??'',leftSource:'File A',rightSource:'File B',fieldMatch:0,similarity:0,status:'MISMATCH'})}return rows}
export function overallSimilarity(rows=[]){if(!rows.length)return 0;return Math.round((rows.reduce((n,r)=>n+Number(r.similarity||0),0)/rows.length)*100)/100}
